### ISSUE TITLE
REJACT가 너무합니다

### ISSUE THREAD

**Issue by eunjung0613** [debug-2357/debug-assignment-00#3]
## :star:Issue

> [#2 ]의 rejact에 상처를 받아 이슈를 생성합니다. 이슈 템플릿에 대해서도 나중에 공부해봅시다 여러분!

## :star:Task

- [x] merge 완료하기
- [x] rejact에 수정 후 다시 request하기
- [x] issue 생성하기
- [x] rejact에 상처받아 이슈 생성 후 템플릿 알려주기

**Comment by icaros7** [comment]
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/5444000/204137783-1fd82180-f942-4321-9a79-81dac0722c89.png">
